// ============================================================
// Data Loader — Load JSON data files
// ============================================================
//
// loadCourses / loadPrereqs read the bundled course + prereq datasets
// under `packages/engine/src/data/`. loadSchoolConfig reads
// `data/schools/<schoolId>.json` at the repo root with `_meta`
// validation, re-exported from `data/schoolConfigLoader.ts`.
// ============================================================
import type { Course, Prerequisite, ConfidenceTier } from "@nyupath/shared";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type Season = "fall" | "spring" | "summer" | "january";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, "data");

export function loadCourses(): Course[] {
    const raw = readFileSync(join(DATA_DIR, "courses.json"), "utf-8");
    return JSON.parse(raw) as Course[];
}

export function loadPrereqs(): Prerequisite[] {
    const raw = readFileSync(join(DATA_DIR, "prereqs.json"), "utf-8");
    return JSON.parse(raw) as Prerequisite[];
}

/**
 * Task 1.8 / PLAN-1 — wire courses-offerings.json so terms-offered is
 * enforced by the solver. Returns a map from courseId to { termsOffered,
 * confidence }. The solver consults this via SolverInput.offerings and
 * SolverInput.offeringConfidence; previously those maps were always empty.
 */
export function loadOfferings(): Map<string, { termsOffered: Season[]; confidence: ConfidenceTier }> {
    const raw = readFileSync(join(DATA_DIR, "courses-offerings.json"), "utf-8");
    const obj = JSON.parse(raw) as Record<string, { termsOffered: Season[]; confidence: ConfidenceTier }>;
    const out = new Map<string, { termsOffered: Season[]; confidence: ConfidenceTier }>();
    for (const [id, v] of Object.entries(obj)) {
        out.set(id, { termsOffered: v.termsOffered, confidence: v.confidence });
    }
    return out;
}

/**
 * Step 8d PR-2 — bulletin credits for courses OUTSIDE the undergraduate
 * planning catalog (graduate/professional), keyed by courseId. Used solely
 * to resolve an explicit student PIN of an off-catalog course so the solver
 * places it with real credits + a "verify in Albert" caveat instead of
 * dropping it. Generated by tools/bulletin-parser/extractCourses.ts.
 */
export function loadOffCatalogCredits(): Map<string, { title: string; credits: number }> {
    const raw = readFileSync(join(DATA_DIR, "off-catalog-credits.json"), "utf-8");
    const obj = JSON.parse(raw) as Record<string, { title: string; credits: number }>;
    const out = new Map<string, { title: string; credits: number }>();
    for (const [id, v] of Object.entries(obj)) {
        out.set(id, { title: v.title, credits: v.credits });
    }
    return out;
}

// ---- School config loader ----
export {
    loadSchoolConfig,
    loadSchoolConfigStrict,
    type SchoolConfigLoadResult,
} from "./data/schoolConfigLoader.js";
